import { Raleway } from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import Script from 'next/script';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Lumasia App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={raleway.className}>
        {children}
        <Script
          src="https://kit.fontawesome.com/b87096f3ef.js"
          strategy="lazyOnload"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
