import { Raleway } from "next/font/google";
import './globals.css'

const inter = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Lumasia App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
